### ISSUE TITLE
As a server admin, I want a restful interface for most operations

### ISSUE THREAD

**Issue by rooshilp** [CMPUT410W15T02/CMPUT410W15-project#5]

**Comment by ftyau** [comment]
Accessed through:

GET:
127.0.0.1:8000/api/author/posts
127.0.0.1:8000/api/posts
127.0.0.1:8000/api/author/AUTHOR_ID/posts
127.0.0.1:8000/api/posts/POST_ID
127.0.0.1:8000/api/friends/AUTHOR1/AUTHOR2

POST:
127.0.0.1:8000/api/friends/AUTHOR_ID
127.0.0.1:8000/api/friendrequest

Takes and responds with the format specified in 
https://github.com/abramhindle/CMPUT404-project-socialdistribution/blob/master/example-article.json
